name: Auto-release latest vim syntax file

permissions:
  contents: write

env:
  SCRIPT_PATH: 'generate_vim_syntax.py'
  OUTPUT_PATH: 'tibasic.vim'

on:
  push:
    paths:
      - "*.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: set env
        run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: execute py script
        run: python "${{ env.SCRIPT_PATH }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag: "${{ env.NOW }}"
          fail_on_unmatched_files: true
          files: "${{ env.OUTPUT_PATH }}"
