name: Auto-release latest vim syntax file

env:
  SCRIPT_PATH: 'generate_vim_syntax.py'
  OUTPUT_PATH: 'tibasic.vim'

on:
  push:
    paths:
      - "*.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: execute py script
        run: python "${{ env.SCRIPT_PATH }}"

      - name: set env vars for release tag name
        run: |
          echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.NOW }}_${{ env.sha_short }}"
          fail_on_unmatched_files: true
          files: "${{ env.OUTPUT_PATH }}"
